# Generated by Django 4.2.5 on 2023-10-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
                ('c_number', models.CharField(max_length=16)),
            ],
        ),
    ]
