# Generated by Django 4.2.5 on 2023-10-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='passwd',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
