# Generated by Django 4.2.5 on 2023-11-04 20:11

import account_setup.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_setup', '0002_customerinfo_passwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='email_id',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, validators=[account_setup.models.Vehicle.validate_capital_or_digit, django.core.validators.MinLengthValidator(17), django.core.validators.MaxLengthValidator(17)])),
                ('model', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)])),
                ('color', models.CharField(max_length=10)),
                ('mfg_company', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Crossover', 'Crossover')], max_length=10)),
                ('customer_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_setup.customerinfo')),
            ],
        ),
    ]
