# Generated by Django 4.2.5 on 2023-11-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_setup', '0003_remove_customerinfo_id_alter_customerinfo_email_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='type',
            new_name='vtype',
        ),
    ]
