# Generated by Django 4.2.5 on 2023-11-04 21:12

import account_setup.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_setup', '0004_rename_type_vehicle_vtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('pincode', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='id',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(max_length=17, primary_key=True, serialize=False, validators=[account_setup.models.Vehicle.validate_capital_or_digit, django.core.validators.MinLengthValidator(17), django.core.validators.MaxLengthValidator(17)]),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Maintenance and Repairs', 'Maintenance and Repairs'), ('Diagnostic Services', 'Diagnostic Services'), ('Body and Paint Services', 'Body and Paint Services'), ('Detailing Services', 'Detailing Services'), ('Customization Services', 'Customization Services'), ('Towing and Recovery Services', 'Towing and Recovery Services'), ('Pre-Purchase Inspection', 'Pre-Purchase Inspection'), ('Rental and Leasing Services', 'Rental and Leasing Services'), ('Consultation and Advice', 'Consultation and Advice')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_setup.vehicle')),
            ],
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('service_type', 'vehicle_type'), name='composite_pk'),
        ),
    ]
