# Generated by Django 4.2.5 on 2023-11-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_setup', '0005_location_remove_vehicle_id_alter_vehicle_vin_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='vehicle_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Crossover', 'Crossover')], max_length=30),
        ),
    ]
