# Generated by Django 4.2.5 on 2023-11-13 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_setup', '0006_alter_service_vehicle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('vehicle_id', models.CharField(max_length=17)),
                ('vehicletype', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('service_details', models.CharField(max_length=250)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('customer_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_setup.customerinfo')),
            ],
        ),
    ]
