# Generated by Django 4.2.5 on 2023-11-13 23:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_setup', '0007_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerInfo',
            fields=[
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('acc_number', models.CharField(max_length=16)),
                ('salary', models.IntegerField()),
                ('SSN', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)])),
                ('passwd', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='manager_finish_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='manager_start_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TechnicianInfo',
            fields=[
                ('SSN', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)])),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('acc_number', models.CharField(max_length=16)),
                ('hourly_rate', models.IntegerField()),
                ('hire_date', models.DateField()),
                ('passwd', models.CharField(max_length=256, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_setup.location')),
                ('mngr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_setup.managerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_detail', models.CharField(max_length=250)),
                ('completed', models.BooleanField(default=False)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_setup.appointment')),
            ],
        ),
    ]
