# Generated by Django 4.2.5 on 2023-11-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_setup', '0009_rename_a_id_appointmentstatus_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianinfo',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
