# Generated by Django 4.2.5 on 2023-11-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_setup', '0012_technicianskills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianinfo',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='technicianinfo',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
