# Generated by Django 4.2.5 on 2023-11-21 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_setup', '0013_remove_technicianinfo_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentstatus',
            name='completed_by_technician',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account_setup.technicianinfo'),
        ),
    ]
