# Generated by Django 4.2.5 on 2023-11-21 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_setup', '0014_appointmentstatus_completed_by_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentstatus',
            name='completed_by_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account_setup.technicianinfo'),
        ),
    ]
